### ISSUE TITLE
Move store logic from app to store folder

### ISSUE THREAD

**Issue by boodland** [chaynHQ/bloom-frontend#1019]
Sub issue of #702 

Move app/ folder content to store/ folder (the app router uses app/ folder as convention to have the pages and layouts, I think moving any other logic outside is recommended as drives to a cleaner and more focused structure

**Comment by boodland** [comment]
Hi @kyleecodes

I have started with #702, I need to create sub issues to tackle the parent one, I am also updating the comment with the proposal with the link of the sub issue to track the progression. 
Can you please assign it to me?

Thanks!

**Comment by eleanorreem** [comment]
@boodland can you tag me and @annarhughes for these PRs.  Thank you! 🙏

**Comment by boodland** [comment]
> @boodland can you tag me and @annarhughes for these PRs. Thank you! 🙏

Hi @eleanorreem, I have mention you both in the PR #1020, I think thats what you mean about tagging.
