### ISSUE TITLE
Update requested issues in Contributing Guide

### ISSUE THREAD

**Issue by kyleecodes** [chaynHQ/bloom-frontend#1039]
### Overview
This is a no-code documentation issue, ideal for contributors new to open-source. 

### Action Items
In our Contributing Guidelines (the `CONTRIBUTING.md` file), under the "**What kind of contributions does Chayn want?**" headline, update the list of issues to:

```
- additional software tests / test coverage
- dependency updates *check Dependabot pull requests 
- code (requested features, bug fixes, quality enhancements, maintenance help)
- accessibility and language support.
- no-code (documentation, translations) *see spam policy below for accepted documentation changes.
```
Notice there is a spelling mistake in "documentation", you should fix this by copy pasting the text above.

### Resources/Instructions

- [How to Write in Markdown Guide](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

**Comment by AhmedFaizanDev** [comment]
hey @kyleecodes could please assign this to me :)

**Comment by kyleecodes** [comment]
Hi @AhmedFaizanDev. Thank you for your interest! 
This issue has the `reserved-volunteers` label, meaning it is reserved for contributors in our volunteer program. Check out our other issues and stay tuned for more.  If interested, you can [explore more ways to get involved with Chayn](https://www.chayn.co/get-involved). Thanks again!

**Comment by AsthaShaw** [comment]
Hi Kylee, can I take this up!
