### ISSUE TITLE
Ensure page title is set on all bloom pages. 

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#1043]
### Overview
Currently the metadata title of every page is just set to `Bloom`. See [_app.tsx](https://github.com/chaynHQ/bloom-frontend/blob/develop/pages/_app.tsx) line 82.  We would like for this to be set to the same as the actual title of the page i.e. on the `/grounding` page, the title would be `Grounding`. 

### Action Items

- [ ] Ensure every page metadata title is set to be the actual title of the page. 
- [ ] Tag @eleanorreem and @annarhughes to review

### Resources/Instructions
- [ ] https://medium.com/@codingbeautytutorials/nextjs-set-page-title-meta-description-24f729dadb85

**Comment by Vishnu21710** [comment]
Hi @eleanorreem and @annarhughes,

I'd like to work on this issue. Please assign it to me.

Thank you!
