### ISSUE TITLE
Page Router E2E Tests

### ISSUE THREAD

**Issue by boodland** [chaynHQ/bloom-frontend#1089]
Sub issue of #702

As discussed in #1064
E2E tests of the current pages should be created in order to migrate from pages router to app router more confident.

The pages to cover with E2E tests are:

- account #1099
- admin #1101
- api
- ~~auth~~  Already enough covered with the existing create/delete-user-* tests
- courses Already enough covered with the existing user-course-session-behaviour tests
- partner-admin #1102
- partnership
- subscription #1103 
- therapy Already enough covered with the existing therapy-usage tests
- welcome #1092
- [slug] Already enough covered with the existing activities and grounding-exercises tests
- 404 Already covered but skipped due to an issue in the dev server
- 500 #1111
- about-our-courses #1109
- action-handler #1110
- chat #1115
- index #1098
- maintenance #1112
- meet-the-team #1090
- sitemap #1116

If a test already exists for the page, add missing tests if required.

**Comment by boodland** [comment]
@kyleecodes, @eleanorreem or @annarhughes assign it to me please.

**Comment by eleanorreem** [comment]
@boodland sorry i missed all these questions!
don't worry about having a test for  /partnership/badoo or /partnership/bumble or /partnership/fruitz and also /api/preview.

**Comment by eleanorreem** [comment]
Thanks I'll mark this as complete! Everything you have done so far should safeguard enough. ⭐
