### ISSUE TITLE
Remove concept of liveCourseAccess from Course Card

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#1176]
### Overview
We used to have a concept of a "Live course".  This was a course that was being delivered live rather than being available online for everyone at any time. This concept has been retired and we want to remove it from the code to simply. This ticket is to remove the concept of liveCourse from the CourseCard component.

### Action Items

- [ ] Remove liveCourseAccess concept from the CourseCard component. 
- [ ] Check everything looks right on /course page
- [ ] Run cypress tests to ensure that everything is working.

**Comment by eliezerjoel** [comment]
Hello here,
I hope I can get this done
Please assign me
