### ISSUE TITLE
Bump terser from 5.12.0 to 5.14.2 

### ISSUE THREAD

**Issue by swetha-charles** [chaynHQ/bloom-frontend#402]
Dependabot has already raised a [PR ](https://github.com/chaynHQ/bloom-frontend/pull/401) for this. 

Please also read through [this](https://www.notion.so/chayn/Tech-volunteer-wiki-5356c7118c134863a2e092e9df6cbc34#fca2430ce2ed47aca341a823935b9587) part of the volunteer wiki to get more information on how to complete dependency upgrade issues. 

**Approach**
- Clone the branch raised by dependabot to your local computer  
- Run up both bloom-backend and bloom-frontend to ensure that this change in dependency has not affected the site
- Run unit tests to ensure they're all passing
- Run cypress tests to ensure they're all passing 
- Commit any changes to the branch and push up
- Comment on the ticket that this change has been verified and request reviews from the team (@swetha-charles or @eleanorreem)

**Comment by dorkele** [comment]
Hey, I will take on this issue :)
