### ISSUE TITLE
Write cypress test for login flow

### ISSUE THREAD

**Issue by swetha-charles** [chaynHQ/bloom-frontend#412]
To get started, read through [this document](https://www.notion.so/chayn/Tech-volunteer-wiki-5356c7118c134863a2e092e9df6cbc34#74cea77f4fcc429d83ad253303fd944e) to get more information on how Cypress is used in Bloom. 

Once you feel comfortable with Cypress and have created an example e2e test as outlined in the Cypress guides, please ping the team to get more information on how to write this ticket :)

**Comment by eleanorreem** [comment]
As an update to this ticket.

The login flow is:
- Hit the home page
- Click on 'log in' in the nav bar. 
- Type in email address and password
- Click log in
- You should then arrive at the courses page 
Note that the cypress tests works against staging so stubbing the request might not work (can't think off the top of my head whether it will). You might need to create a user in staging to get the login flow to work. 
Let me know if you have any questions.
