### ISSUE TITLE
Create maintenance page

### ISSUE THREAD

**Issue by swetha-charles** [chaynHQ/bloom-frontend#413]
## User story

As a Bloom user, I want to know when Bloom is down for maintenance.

## Background

Currently if we have a period of down time on Bloom backend we don’t have any mechanism to inform our users. They just have a poor user experience and see errors.

## Proposal

- create a page that tells the user that the site is down for maintenance according to these designs below. We don’t need it to be beautifully accurate. We just need it functional.
- It should be turned off and on with a feature flag (see user research banner as an example)
- It should override all pages when turned on. i.e. if the feature flag is on. All pages should be redirected to the main
- The Nav bar should be just as if one is logged out (i.e. don’t worry too much about what appears)
- Under the hood there are a couple of design options. Please choose whichever you prefer:
    1. When the feature flag is on, redirect all users to a /maintenance page. When the feature flag is off, all users are redirected from /maintenance to home page. 
    2. When feature flag is on, override  the content of whatever the page the user has on. This is so when they refresh and the feature flag is turned off, they return to the same page they originally tried to access.## User story

As a Bloom user, I want to know when Bloom is currently not usable and when it will be back. 

### Designs 
    
<img width="106" alt="Screenshot 2022-12-29 at 16 34 56" src="https://user-images.githubusercontent.com/16049515/209983336-f57fb934-1d4b-4129-9008-a8868e646f1a.png">

    
<img width="401" alt="Screenshot 2022-12-29 at 16 34 51" src="https://user-images.githubusercontent.com/16049515/209983329-e026f1ce-3e21-4a38-a92e-b96b1097cb1a.png">

### Assets 
![securicray copy](https://user-images.githubusercontent.com/16049515/209983399-019a7b2f-d5e9-4811-a726-907221957283.png)

**Comment by eleanorreem** [comment]
## User story

As a Bloom user, I want to know when Bloom is currently not usable and when it will be back. 

## Background

Currently if we have a period of down time on Bloom backend we don’t have any mechanism to inform our users. 

## Proposal

- create a page that tells the user that the site is down for maintenance according to these designs below. We don’t need it to be beautifully accurate. We just need it functional.
- It should be turned off and on with a feature flag (see user research banner as an example)
- It should override all pages when turned on. i.e. if the feature flag is on. All pages should be redirected to the main
- The Nav bar should be just as if one is logged out (i.e. don’t worry too much about what appears)
- Under the hood there are a couple of design options. Please choose whichever you prefer:
    1. When the feature flag is on, redirect all users to a /maintenance page. When the feature flag is off, all users are redirected from /maintenance to home page. 
    2. When feature flag is on, override  the content of whatever the page the user has on. This is so when they refresh and the feature flag is turned off, they return to the same page they originally tried to access.## User story

As a Bloom user, I want to know when Bloom is currently not usable and when it will be back. 

## Background

Currently if we have a period of down time on Bloom backend we don’t have any mechanism to inform our users. 

## Proposal

- create a page that tells the user that the site is down for maintenance according to these designs below. We don’t need it to be beautifully accurate. We just need it functional.
- It should be turned off and on with a feature flag (see user research banner as an example)
- It should override all pages when turned on. i.e. if the feature flag is on. All pages should be redirected to the main
- The Nav bar should be just as if one is logged out (i.e. don’t worry too much about what appears)
- Under the hood there are a couple of design options. Please choose whichever you prefer:
    1. When the feature flag is on, redirect all users to a /maintenance page. When the feature flag is off, all users are redirected from /maintenance to home page. 
    2. When feature flag is on, override  the content of whatever the page the user has on. This is so when they refresh and the feature flag is turned off, they return to the same page they originally tried to access.

### Designs 
    
<img width="106" alt="Screenshot 2022-12-29 at 16 34 56" src="https://user-images.githubusercontent.com/16049515/209983336-f57fb934-1d4b-4129-9008-a8868e646f1a.png">

    
<img width="401" alt="Screenshot 2022-12-29 at 16 34 51" src="https://user-images.githubusercontent.com/16049515/209983329-e026f1ce-3e21-4a38-a92e-b96b1097cb1a.png">

### Assets 
![securicray copy](https://user-images.githubusercontent.com/16049515/209983399-019a7b2f-d5e9-4811-a726-907221957283.png)

**Comment by anmol-fzr** [comment]
Hey @kyleecodes is would like to contribute to this. Please assign me this issue

**Comment by kyleecodes** [comment]
Hey @anmol-fzr thank you for your interest!
I can assign you after this [PR](https://github.com/chaynHQ/bloom-frontend/pull/900) is either closed or completed.
Also note that we can only assign one advanced issue per contributor at a time.
 As per our Issue Limit policies, sometimes we have to limit the number of issues assigned to help keep a sustainable flow of issues for all contributors. 
Thank you!
