### ISSUE TITLE
Remove PWA as it is not used 

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#433]
**Background**
We installed next-pwa a few months back so that our site could be a progressive web app. However, we haven't worked on it since then and are unlikely to in the near future. At the moment it is broken which means it is causing a lot of noise in our logs and is causing software bloat so we would like to remove it. 

**Task** 
- uninstall next-pwa 
- remove any code to do with next-pwa
- Test happy paths

**Comment by rabbanirizwan** [comment]
@ I wanted to worked on this

**Comment by hellenward** [comment]
Hi, I will pick this up :)

**Comment by swetha-charles** [comment]
This is open for pickup

**Comment by PatriciaRosalis** [comment]
Hi! I will work on this one (:

**Comment by swetha-charles** [comment]
Fixed by @PatriciaRosalis
