### ISSUE TITLE
Remove unused workflows from .github folder

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#578]
### Overview
Remove .github/manual-deploy-staging and .github/manual-deploy-prod workflows. Both of these workflows do not work so there is no point them cluttering our repo. 

### Action Items
- [ ] Create a branch
- [ ] Remove `.github/workflows/manual-deploy-staging.yml` and `.github/workflows/manual-deploy-prod.yml`
- [ ] Create Pull request 
- [ ] Await review

**Comment by Nkiriobasi** [comment]
Please, can I fix this?

**Comment by nexuspy** [comment]
changes done , can you please look after them @eleanorreem

**Comment by eleanorreem** [comment]
@Nkiriobasi sorry for missing your comment. @nexuspy thanks for the PR. I have approved and will merge once tests pass
