### ISSUE TITLE
Bump word-wrap from 1.2.3 to 1.2.4

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#580]
### Overview
Dependabot [pull request ](https://github.com/chaynHQ/bloom-frontend/pull/549) are automatically created. Our cypress tests don't currently run against code on the branch so we need to run them manually for now. An automated way of doing this is in the pipeline. However, for now we need to run the tests manually

### Action Items

- [ ] Clone the branch raised by dependabot to your local computer
- [ ] Run up both bloom-backend and bloom-frontend to ensure that this change in dependency has not affected the site
- [ ] Run unit tests to ensure they're all passing
- [x] Run cypress tests to ensure they're all passing
- [ ] Commit any changes to the branch and push up
- [ ] Comment on the ticket that this change has been verified and request reviews from the team (@kyleecodes)

**Comment by ldaijiw** [comment]
hi @eleanorreem @kyleecodes please can I pick this ticket up? thanks

**Comment by kyleecodes** [comment]
@ldaijiw Thanks for your interest! The issue has been assigned. 

Please note that you do NOT need to locally run the Cypress tests for this issue, I went ahead and checked that part off in the issue description.

**Comment by kyleecodes** [comment]
Closing this issue because it's been solved in recent app upgrades done by our dev team, thank you for your time!
