### ISSUE TITLE
Bump protobufjs from 6.11.3 to 6.11.4

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#582]
### Overview
Dependabot [pull requests](https://github.com/chaynHQ/bloom-frontend/pull/563)  are automatically created. Our cypress tests don't currently run against code on the branch so we need to run them manually for now. An automated way of doing this is in the pipeline. However, for now we need to run the tests manually

### Action Items

- [ ] Clone the branch raised by dependabot to your local computer
- [ ] Run up both bloom-backend and bloom-frontend to ensure that this change in dependency has not affected the site
- [ ] Run unit tests to ensure they're all passing
- [ ] Run cypress tests to ensure they're all passing
- [ ] Commit any changes to the branch and push up
- [ ] Comment on the ticket that this change has been verified and request reviews from the team (@kyleecodes)

**Comment by Abinash-bit** [comment]
Hey @eleanorreem and @kyleecodes want to contribute to this issue can anyone assign me Please.

**Comment by kyleecodes** [comment]
@Abinash-bit thank you for your interest! You are assigned. :)

**Comment by Abinash-bit** [comment]
Ok thank you @kyleecodes for assigning me this issue.

**Comment by kyleecodes** [comment]
Closing this issue because it's been solved in recent app upgrades done by our dev team, thank you for your time!
