### ISSUE TITLE
Enable Cypress test coverage 

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#583]
### Overview
We would like to know how much of our code is covered by Cypress tests. We don't need this to be part of the CI flow but to run with a command locally. Ideally we would run `yarn cypress:cov` and we would receive a stat for how much code our E2E tests cover. 

### Action Items

- [ ] Research into how to set up Cypress test coverage. 
- [ ] Its likely you will need to install [cypress/code-coverage plugin
](https://docs.cypress.io/guides/tooling/code-coverage#E2E-code-coverage)
- [ ] Make changes to enable code coverage stats
- [ ] Commit/ PR and assign @eleanorreem or @annarhughes  as reviewers

### Resources/Instructions
[Cypress test coverage docs](https://docs.cypress.io/guides/tooling/code-coverage)

**Comment by ckirby19** [comment]
Hello! I would like to pick this up! Thank you :)

**Comment by ckirby19** [comment]
I raised a PR but having a few issues with the code coverage actually being generated. I have added the errors I am getting to the PR and I am really not sure what else I am missing to get this to work. Please have a look when you get a chance, thanks!
