### ISSUE TITLE
Tabs Error in the Console on Home page when logged in

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#584]
**Describe the bug**
When you are logged in and on the home page, you get an error in the console.
```
next-dev.js:20 MUI: The `value` provided to the Tabs component is invalid.
None of the Tabs' children match with "-1".
You can provide one of the following values: 0, 1, 2, 3, 4.
```
This comes from the SecondaryNav component. When we are on the home page, we are not in any of the tabs and the value is set as -1. -1 is not an index in the tabs. 

**To Reproduce**
1. Go to /  in bloom
2. Click on Login in the header 
3. Log in with credentials/ create an account
4. Once logged in return to the home page
5. Look at the console and you will see the error 

**Expected behavior**
We have no error in the console. Ideally we would not set a value at all. If you look at these [[docs](https://mui.com/material-ui/api/tabs/)](https://mui.com/material-ui/api/tabs/) - it looks like you can set the value to false and it will select nothing and we won’t get the error.

**Desktop (please complete the following information):**
 All OS and Browsers

**Comment by IanWorley** [comment]
Hey I know I have another issue assign to me but could I take this one also.

**Comment by IanWorley** [comment]
Hey can someone take me off this issue I had something come up.

**Comment by boodland** [comment]
Happy to fix this issue, assign it to me please.

**Comment by ckirby19** [comment]
Hello, I would like to pick this up if it is available? Thanks!

**Comment by eleanorreem** [comment]
Looks like this is no longer an issue @ckirby19 Thanks! Need to have a better process cleaning up old tickets. Apologies!
