### ISSUE TITLE
Testing: Outside Contributor Updates README.md 

### ISSUE THREAD

**Issue by kyleecodes** [chaynHQ/bloom-frontend#599]
### Overview
Testing outside contributor permissions by updating README.md

### Action Items
Update the README.md by replacing broken CI workflow link with a working one.

Current: [![Bloom CI Pipeline](https://github.com/chaynHQ/bloom-frontend/actions/workflows/ci.yml/badge.svg)](https://github.com/chaynHQ/bloom-frontend/actions/workflows/ci.yml)

New: [![Bloom Frontend CI Pipeline](https://github.com/chaynHQ/bloom-frontend/actions/workflows/deploy-to-prod.yml/badge.svg)](https://github.com/chaynHQ/bloom-frontend/actions/workflows/deploy-to-prod.yml)

**Comment by kfields31** [comment]
Assign me, the test contributor.
