### ISSUE TITLE
Bump tough-cookie from 4.0.0 to 4.1.3

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#609]
### Overview
Dependabot [pull requests](https://github.com/chaynHQ/bloom-frontend/pull/605)  are automatically created. Our cypress tests don't currently run against code on the branch so we need to run them manually for now. An automated way of doing this is in the pipeline. However, for now we need to run the tests manually

### Action Items

- [ ] Clone the branch raised by dependabot to your local computer
- [ ] Run up both bloom-backend and bloom-frontend to ensure that this change in dependency has not affected the site
- [ ] Run unit tests to ensure they're all passing
- [ ] Run cypress tests to ensure they're all passing
- [ ] Commit any changes to the branch and push up
- [ ] Comment on the ticket that this change has been verified and request reviews from the team (@kyleecodes)

**Comment by CaiqueCoelho** [comment]
I would like to work on this. Can you assign it to me?

**Comment by CaiqueCoelho** [comment]
@eleanorreem @kyleecodes quick question about running the front-end locally to run the tests, Do I need the following tokens on my local.env or I can mock those values?

```
NEXT_PUBLIC_FIREBASE_API_KEY=
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=
NEXT_PUBLIC_FIREBASE_PROJECT_ID=
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=
NEXT_PUBLIC_FIREBASE_APP_ID=
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=
```

**Comment by CaiqueCoelho** [comment]
Also do I need the env vars to run the backend locally or can I mock those https://github.com/chaynHQ/bloom-backend#create-env-file?

**Comment by kyleecodes** [comment]
@CaiqueCoelho Yes you will need to gather your own Firebase tokens for both the frontend and backend. We don't have emulators set up to mock those currently. 

Thank you for your interest!

**Comment by kyleecodes** [comment]
Closing this issue because it's been solved in recent app upgrades done by our dev team, thank you for your time!
