### ISSUE TITLE
Add Robot.txt

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#610]
### Overview
We need to give instructions to search engines and crawlers about where they can/ should go through a robot.txt file. 
For now these are the Disallowed urls 

- /admin/dashboard
- /partner-admin/create-access-code
- /account/apply-a-code

### Action Items

- [ ] Create your own branch from develop branch 
- [ ] Follow instructions in the resources listed below
- [ ] Ensure the URLs above are Disallowed
- [ ] Run cypress tests and unit tests locally to ensure nothing is broken
- [ ] Commit and push your PR
- [ ] Create a PR and tag @kyleecodes 

Please disregard failing tests as we are updating their performance. Thank you!

### Resources/Instructions
- See instructions about how to create a [Robot.txt in nextjs](https://nextjs.org/learn/seo/crawling-and-indexing/robots-txt)

**Comment by DustyDogCodex** [comment]
Hi!

I would like to work on this issue. If no one else has been assigned, please assign this issue to me so I can help you resolve it.

Thanks!

**Comment by kyleecodes** [comment]
Thank you for your interest @DustyDogCodex! I have assigned you this issue. :)

**Comment by DustyDogCodex** [comment]
hi @kyleecodes !

Hope you are doing well! I just submitted a PR for this issue. I have additionally added a sitemap.xml.tsx file along with the robots.txt file, following the guide on Nextjs docs. Please let me know if you want me to edit/remove that file.

Thanks!
