### ISSUE TITLE
Bloom CI pipeline badge not working

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#612]
**Describe the bug**
The Bloom CI pipeline on the Readme is broken. 

**To Reproduce**
1. Go to Readme.md
2. Look at the badge for the CI pipeline. 
3. You will see that there is no badge in the screen shot below. 

**Expected behavior**
We should see the "passing" badge as expected on github Repositories. 

**Screenshots**
<img width="414" alt="Screenshot 2023-09-29 at 13 04 29" src="https://github.com/chaynHQ/bloom-frontend/assets/16049515/979ca0f1-619d-4ca9-98fb-4269aec83559">

**Additional context**
- This bug is caused by the old pipeline being deleted. Instead we should be connecting to the deploy to staging pipeline. 
- See resource about [badges](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge)

**Comment by Danishkar** [comment]
can i work on this?

**Comment by kyleecodes** [comment]
> can i work on this?

Yes thank you @Danishkar
