### ISSUE TITLE
Move README.md documentation to new /docs directory

### ISSUE THREAD

**Issue by kyleecodes** [chaynHQ/bloom-frontend#617]
### Overview
We should simplify our README by separating the key concepts and architecture guides into their own separate /docs directory, similar to [how Soulmedicine is organized](https://github.com/chaynHQ/soulmedicine/tree/main/docs), and turn the README into a brief overview of the project and quick start guide. 

### Action Items
- [ ] Create a `/docs` folder in the root directory.
- [ ] Move everything under the Key Concepts section of the `README.md` and before the Cypress section into the `/docs` folder in a file called `key-concepts.md`

**Comment by DustyDogCodex** [comment]
Hi!

I can solve this issue for you. If its still available, please assign this to me and I will knock it out for you.

Thanks!

**Comment by kyleecodes** [comment]
@DustyDogCodex Thank you for your interest! The issue has been assigned to you.

**Comment by DustyDogCodex** [comment]
Hi @kyleecodes ! 

Hope you are having a good day of coding today! I finished resolved this isssue and have submitted a PR for it as well. Please review it when you get a chance and let me know if you need anything else from me!

Thanks!

**Comment by kyleecodes** [comment]
Thank you @DustyDogCodex, hope you're having a good day coding as well!

I have merged your PR, thanks again! :)
