### ISSUE TITLE
Add link to CONTRIBUTING.md file in README.md

### ISSUE THREAD

**Issue by kyleecodes** [chaynHQ/bloom-frontend#618]
### Overview
We need to link to the CONTRIBUTING.md file in the README.md so contributors can more easily see the contributing guidelines.

### Action Items
- [ ] Under the title in Local Development section in the `README.md`, add the following:
"To make a contribution, please read our Contributing Guidelines in CONTRIBUTING.md"
- [ ] Make sure the sentence above contains a Markdown link to the repo's CONTRIBUTING.md file. 

### Resources/Instructions
- [How to Create Markdown Links](https://www.markdownguide.org/basic-syntax/#links)

**Comment by R894** [comment]
Hello, I am interested in working on this Issue, could you assign it to me please?

**Comment by kyleecodes** [comment]
@R894 thanks for your interest! You have been assigned the issue.
