### ISSUE TITLE
Link to our Volunteer Info page in our README.md

### ISSUE THREAD

**Issue by kyleecodes** [chaynHQ/bloom-frontend#623]
### Overview
Currently, our README links interested volunteers directly to the volunteer form, not to our volunteer info page (which contains the form).  We need the README to link to the [Getting Involved volunteer info page](https://www.notion.so/chayn/Get-involved-423c067536f3426a88005de68f0cab19?pvs=4) instead, similar to how our CONTRIBUTING.md file does.

### Action Items
- [ ] Replace the text in the `README.md` under the Getting Involved section:
If you would like to help Bloom and receive special access to our organization and volunteer opportunities, please get in touch with us to express your interest in volunteering via [this form](https://forms.gle/qXfDdPgJxYwvMmVP7)." 
with the following text:
"If you would like to help Chayn and receive special access to our organization and volunteer opportunities, please visit our Getting Involved page."
- [ ] Make sure the above sentence contains a markdown link to our Getting Involved page: https://www.notion.so/chayn/Get-involved-423c067536f3426a88005de68f0cab19?pvs=4 

Please disregard failing tests as we are updating their performance. Thank you!

### Resources/Instructions
- [How to make Markdown Links](https://www.markdownguide.org/basic-syntax/#links)

**Comment by strawHat121** [comment]
This seems something which can be done easily.

Can I take this up if you don't mind ?

**Comment by kyleecodes** [comment]
Thank you for asking @strawHat121, yes you have been assigned the issue. :)
