### ISSUE TITLE
Link the /docs folder in the README.md

### ISSUE THREAD

**Issue by kyleecodes** [chaynHQ/bloom-frontend#624]
### Overview
We have recently created a `/docs` directory in this repo to store technical documentation separate from the README.md and we need to link contributors to this directory in the `README.md`, similar to [how Soulmedicine is organized](https://github.com/chaynHQ/soulmedicine/tree/main/docs).

### Action Items
- [ ] Write the following sentence under the "Bloom Frontend" section title in the `README.md`:
"For a more detailed explanation of this project's key concepts and architecture, please visit the /docs directory."
- [ ] Make sure the above sentence contains a Markdown link to the `/docs` directory, which would be: https://github.com/chaynHQ/bloom-frontend/tree/develop/docs (This is where a README.md file will be located in the near future.)

Please disregard failing tests as we are currently upgrading their performance. Thank you!

Resources:
- [How to make Markdown Links](https://www.markdownguide.org/basic-syntax/#links)

**Comment by IanWorley** [comment]
Hey could I take this issue @kyleecodes

**Comment by FreemRL** [comment]
Hi I created PR for this :) (#625)

**Comment by kyleecodes** [comment]
Hey @FreemRL, thank you for your PR! But for no-code, good first issues, asking before submitting a PR is required, as per the `CONTRIBUTING.md` file states.

**Comment by kyleecodes** [comment]
@IanWorley Yes you may take this issue, it is now assigned to you.

**Comment by FreemRL** [comment]
Okay sorry my bad @kyleecodes
