### ISSUE TITLE
Dynamic route generation for /courses route in sitemap or other alternatives?

### ISSUE THREAD

**Issue by DustyDogCodex** [chaynHQ/bloom-frontend#637]
### Overview
Currently the /courses routes are hidden behind a login page, which will prevent some web crawlers to access and index it. I am proposing some alternatives to allow some of this content to be accessed by web crawlers for better SEO and would love dev feedback on the best way forward
 
### Action Items

While working on issue #610 , I noticed that /courses is protected behind a login page. I added some code to dynamically add /courses routes to the sitemap for the project which would help in better SEO for the website.

On @kyleecodes 's recommendation, I am opening this issue for gathering dev feedback on the best way forward. Here are some ideas/alternatives I proposed in my original comment while talking with Kylee.

> So currently I have static routes manually entered in the sitemap and some code for representing the dynamic routes under /courses. As the /courses routes are being login access, web crawlers cannot access them UNLESS the web crawlers use some specialized package/code to use login credentials and view /courses. Here we have two options:

> If you want the /courses routes to not be accessible to web crawlers, I can add them to the disallow list in robots.txt!

> If you do want the /courses routes to be accessible to web crawlers, I can figure out how to get dynamic route paths from getStaticProps and replace my current code for adding these routes to the sitemap. From my understanding, if I implement this correctly, everytime a new course is added, the sitemap would automatically be updated with the route for that course withoute needing manual editing of the sitemap.

> Alternatively, if you would like the /course route to be protected from web crawlers yet still have some data on courses available for SEO, I can create a new route for just displaying some course info on the frontend. That way you can choose what gets displayed and this route will be a static route that doesn't need to be updated, nor is it behind login access. This route would be like a sneak peek or a welcome brochure to the courses without showing everything in them if that makes sense? Just something for the web crawlers to look at and know what the website's about and what it's offering.

I would love to get some feedback on whether or not to disallow /courses from robots.txt, add it to the sitemap or to create a small courses page which will display info on the courses so web crawlers can index it. I am not privy to the contents of these courses so I can not make the call whether they should be hidden from web crawlers or not.

### Resources/Instructions

- Creating dynamic sitemaps in Next 12
https://nextjs.org/learn/seo/crawling-and-indexing/xml-sitemaps\
https://claritydev.net/blog/nextjs-dynamic-sitemap-pages-app-directory

**Comment by kyleecodes** [comment]
> I would love to get some feedback on whether or not to disallow /courses from robots.txt, add it to the sitemap or to create a small courses page which will display info on the courses so web crawlers can index it. I am not privy to the contents of these courses so I can not make the call whether they should be hidden from web crawlers or not.
> 

Thank you for creating this issue! This all looks good to me.
Tagging @eleanorreem for approval on whether or not to add web crawlers to courses to boost SEO.

**Comment by eleanorreem** [comment]
Hi @DustyDogCodex sorry for the delay. Thanks so much for the suggestion. It's a big thumbs up from the team for indexing our courses! My thoughts are if you can add dynamic courses through getStaticProps that would be ideal.

**Comment by DustyDogCodex** [comment]
Hi @eleanorreem ,

Sounds good to me! I'll get started on that right away!

Cheers
