### ISSUE TITLE
Enable Super Admin users to update the status of Partner Admin users from active to inactive

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#639]
### Overview
Enable Super Admin users to update the status of Partner Admin users from active to inactive. This will happen on the `/admin/dashboard` page. 

### Action Items

- [ ] Ensure you have a few super admin and partner admin users created in Bloom-backend.

**Initial State on page load**

- [ ] Additional Card has been added with Title, Autocomplete Input and Button. The form field should require more than 3 letters before displaying options. 
- [ ] Get Autocomplete Options from the backend. See the implementation of UpdateTherapyAdminForm. I would like the autocomplete form to work like that form with a debounced asynchronously populated options list. To populate the options field, you will need to send a request to GET /users like the UpdateTherapyAdminForm with the searchQuery that includes the "partner-admin" relation and with partnerAdmin.partnerAdminId field as "IS NOT NULL" (See UpdateTherapyAdminForm if this is not clear).
<img width="450" alt="Screenshot 2023-10-13 at 14 11 47" src="https://github.com/chaynHQ/bloom-frontend/assets/16049515/c4d980da-d47a-428b-a19f-261e687f6cf5">

**Once the user email is selected**

- [ ] Render a checkbox, prefilled with the current state of the partner admin user. I.e. if they are active currently, the checkbox would be filled. 
- [ ] Once the user checks or unchecks the box and presses the submit button. Send the relevant request to PATCH /partner-admin/:id 
- [ ] Create some sensible error messages. We aren't too prescriptive about error states. If you loosely follow that pattern of UpdateTherapyAdminForm, that should be enough. 

<img width="448" alt="Screenshot 2023-10-13 at 14 11 54" src="https://github.com/chaynHQ/bloom-frontend/assets/16049515/1f44010e-b94e-45aa-bd14-a9a1b4090f23">

**Once the request has been successful**

- [ ] Display Success Text
- [ ] Ensure user can reset the form with the "Update another partner admin" form

<img width="444" alt="Screenshot 2023-10-13 at 14 12 00" src="https://github.com/chaynHQ/bloom-frontend/assets/16049515/932edefb-567b-4f5c-aaf4-5618b02e0af8">

Please note this ticket is dependent on this ticket in the [backend](https://github.com/chaynHQ/bloom-backend/issues/340) to be completed.

**Comment by SangilYun** [comment]
Hi @eleanorreem this looks fun! can I work on this?

**Comment by kyleecodes** [comment]
Hey @SangilYun! Awesome you are now assigned.

**Comment by SangilYun** [comment]
@eleanorreem Correct me if I'm wrong but current backend implementation([link](https://github.com/chaynHQ/bloom-backend/blob/b9ef6c67f0aa4e7cdbec2cf21bf0a4ba4a4e9f71/src/user/user.service.ts#L427)) doesn't seem to be able to handle `IS NOT NULL` passed as `partnerAdmin.partnerAdminId`.

This change ([link](https://github.com/chaynHQ/bloom-backend/pull/410)) might have affected what we have in the description.

**Comment by kyleecodes** [comment]
Good question. I pinged Chayn developers. Some are off this week so there is a response delay. Thank you for your patience.

**Comment by eleanorreem** [comment]
Hey @SangilYun, Thanks for your question! It looks like there was some oversight in the backend ticket and it should have handled isNotNull. Sorry about that. I think we would want to be able to get all partner admins (active or inactive) so passing in `active: true` would not be enough. I will make a ticket to cover this in the backend. This might be a blocker for a little bit!

**Comment by eleanorreem** [comment]
I have added a [backend ticket ](https://github.com/chaynHQ/bloom-backend/issues/443) to unblock you.
