### ISSUE TITLE
Custom 404 pages do not work on the dev server

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#641]
**Describe the bug**
Our custom 404 pages are not working on the dev server but they do seem to work if you build the app. This only happened after the upgrade to nextjs 13.5.4 

**To Reproduce**
1. Run the bloom-frontend with `yarn dev`.
2. go to localhost:3000/123
3. See default Next js 404 page. 
4. Exit dev server 
5. Run `yarn build`
6. Run `yarn start`
7. go to localhost:3000/123 
8. See Custom 404 page which is src/pages/404.tsx 

**Expected behavior**
On the dev server, we should be able to see the custom 404 page. 

**Screenshots**
Nextjs Default
<img width="1472" alt="Screenshot 2023-10-16 at 11 17 38" src="https://github.com/chaynHQ/bloom-frontend/assets/16049515/61762727-f95a-451c-8a9c-de45723eec93">
Custom 404
<img width="1228" alt="Screenshot 2023-10-16 at 11 21 39" src="https://github.com/chaynHQ/bloom-frontend/assets/16049515/97868c3c-4ae3-4cb5-99ff-b09fdc922aa6">

**Desktop (please complete the following information):**
 - Macbook Pro 2021, Mac Os Monterey 12.2 
 - Browser Chrome 
 - Version 117.0.5938.132

**Comment by sriabhinay556** [comment]
is this issue still open?

**Comment by eleanorreem** [comment]
I think this ticket was fixed in a recent upgrade so i am going to close. THanks for your interest @sriabhinay556 !
