### ISSUE TITLE
NextJS: Upgrade to version 14

### ISSUE THREAD

**Issue by kyleecodes** [chaynHQ/bloom-frontend#704]
### Overview
While [NextJS 13 will be supported for the forseeable future](https://nextjs.org/blog/next-13#new-app-directory-beta), we should consider upgrading to NextJS 14 to leverage NextJS's newest features and 14's stronger support for bug fixes and security patches.

### Action Items
- [x] Upgrade to Node 18: https://github.com/chaynHQ/bloom-frontend/issues/703 to unblock.
- [ ] Check for any issues and pull requests opened by dependabot to update nextjs / react.
- [ ] Follow this guide to upgrade to 14: [NextJS Docs: Upgrading to 14](https://nextjs.org/docs/pages/building-your-application/upgrading/version-14)
- [ ] Run all tests and report any errors here. If there are many or highly complex errors, we will open new issues for them. Otherwise, please resolve these errors.

### Resources/Instructions
- [NextJS Blog: Introducing 14](https://nextjs.org/blog/next-14)
- [Medium blog post: Should I update my app to Next 14?](https://medium.com/@moh.mir36/should-you-update-my-app-to-next-14-280b99cfa178#:~:text=In%20Next.,directly%20within%20your%20React%20components.)

**Comment by jackdraks** [comment]
Assign this issue to me .

**Comment by kyleecodes** [comment]
@jackdraks You are assigned!

**Comment by kyleecodes** [comment]
Hey @jackdraks! It's been 1 month since any updates.
Would you like to keep working on this issue?
Totally understand if you need more time or if things came up and you cannot complete this issue anymore.

If you have any questions, please let us know here and we're happy to help!

**Comment by boodland** [comment]
Hi @kyleecodes this issue can be closed as it is already solved

<img width="1724" alt="image" src="https://github.com/user-attachments/assets/86e847d0-6be5-42c3-99de-40ee5214e993">
