### ISSUE TITLE
French Create User Test 

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#838]
### Overview
All our testing is currently in english and we want to ensure our other site languages are working. This need came from an incident where a bug happened on all browser languages except for english and the cypress tests did not catch it.

### Action Items

- [ ] Get Cypress tests up and running. See [Cypress Readme](https://github.com/chaynHQ/bloom-frontend/blob/develop/CYPRESS.md)
- [ ] Create your own branch 
- [ ] Take a look at this [german example](https://github.com/chaynHQ/bloom-frontend/blob/develop/cypress/integration/create-user.de.cy.tsx) of the test 
- [ ] Duplicate this test in French and name it create-user.fr.cy.tsx. Note that you will have to update some of the test assertions to match the spanish version of the site. Take a look at bloom.chayn.co/fr for the french version of the site to find the equivalent text. 
- [ ] See notes below for helpers
- [ ] Commit and push your changes and create a PR.
- [ ] Tag @eleanorreem  for a review 

### Resources/Instructions
- [Cypress readme](https://github.com/chaynHQ/bloom-frontend/blob/develop/CYPRESS.md)
- Ensure you create a custom visitFrenchPage that replicates the behaviour of visitGermanPage in [this file](https://github.com/chaynHQ/bloom-frontend/blob/develop/cypress/support/commands.js)
- You will also have to update the [type file](https://github.com/chaynHQ/bloom-frontend/blob/develop/cypress/support/index.d.ts)

**Comment by LucasVermersch** [comment]
Hi @eleanorreem I can take this if you want, it will be my first contribution in a open source project 😄

**Comment by kyleecodes** [comment]
Hey @LucasVermersch, thank you for your interest! I have assigned you this issue.
Be sure to check out our [Contribution Guidelines](https://github.com/chaynHQ/bloom-frontend/blob/develop/CONTRIBUTING.md). 🙂
