### ISSUE TITLE
Cypress test for user register errors

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#852]
### Overview
We had a bug which affected user sign up errors. We had no cypress tests to ensure that users were getting helpful notifications for why they were unable to make an account. 
### Action Items
- [ ] pull most recent changes and create your own branch
- [ ] ensure cypress tests are up and running
- [ ] Take a look at create-user.tsx. You will be adapting the create-user.cy.tsx test to include the following scenarios:
- [ ] Test scenario 1: a user tries to log on with the email for an account that already exists. You can use one of the email addreses from the cypress env. The user should get an error saying that this account exists
- [ ] Test scenario 2: a user tries to create an account with the password '123'. The user should get an error which indicates they need a stronger password
- [ ] Test scenario 3: a user tries to create an account with an email of 'test@test'. They should get an error saying the email is not correct. 
- [ ] Ensure all tests are passing
- [ ] Push and make a PR and tag @eleanorreem 

### Resources/Instructions

- [How to set up cypress for bloom](https://github.com/chaynHQ/bloom-frontend/blob/develop/CYPRESS.md)

**Comment by austinthaldorfhuelsbeck** [comment]
Hello @eleanorreem and @kyleecodes ! I found Bloom while searching for open source projects to contribute to. I would love to get started with contributing and this looks like a great place to start. I noticed in the contribution guide that claiming an issue is recommended, so I wanted to introduce myself and express my interest in this issue.

**Comment by kyleecodes** [comment]
Thank you @austinthaldorfhuelsbeck for your interest in contributing to Chayn!
I have assigned you the issue. Please let us know if you have any questions, happy to help.

Happy Coding!

**Comment by kyleecodes** [comment]
Hey @austinthaldorfhuelsbeck! Checking in to see if you would like to keep working on this issue? Totally understand if you need more time or if things came up and you cannot complete this issue anymore.

If you have any questions, we're happy to help!

**Comment by ckirby19** [comment]
Hi, I am part of the Chayn tech volunteers group and I would like to be assigned to this task please :)

**Comment by ckirby19** [comment]
Brief update: just getting the cypress tests up and running locally, should have a PR ready for this ticket by the end of the week. Thanks!

**Comment by kyleecodes** [comment]
@ckirby19 thank you for the update!
We just updated the [Chayn Tech Contributor Guide](https://www.notion.so/chayn/Chayn-Tech-Contributor-Wiki-5356c7118c134863a2e092e9df6cbc34?pvs=4#1e51da106e1a484baf1429a04be71388) with directions on how to obtain some of the required Cypress variables, it may be of some help.
