### ISSUE TITLE
Create script to check translations have been provided 

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#890]
### Overview
As a dev, I get helpful warnings if I forgot to add a translation file or to paste translations in the relevant files. 

Currently, when an english translation file is added to the /messages folder for a new page, the spanish / hindi equivalent could easily be missed. It would be great to run a script to check that all the files match up. 

### Action Items
- [ ] Add a script which checks that our translation files are correct. 
This script needs to check that
- [ ] for each enabled language that the messages .json files exist for every folder. i.e. shared/en.json, shared/hi.json etc.. all exist.
- [ ] for each file, ensure there is a matching key value pair in every file. 
- [ ] if either of these is not true, print a warning mentioning, language and the key. 
- [ ] Add the script to the package json. It should be called something like "check:translations".

**Comment by anmol-fzr** [comment]
@eleanorreem 
Hi!, Could you please assign me an issue to work on for the bloom-frontend project ? I'm eager to contribute to the project and the society.
