### ISSUE TITLE
Add GA events to storyblok buttons

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#891]
### Overview
We want to send events every time someone clicks a button so we know how our buttons are used. We have events on most buttons but not those dynamically created by storyblok. See bloom-frontend/components/storyblok/StoryblokButton.tsx. 

### Action Items
- [ ] Add an onclick event that tracks the button press. 
- [ ] The event should be STORYBLOK_BUTTON_[TITLE]_CLICKED. Please dynamically replace the title with the button content. 
- [ ] Please seebloom-frontend/components/layout/LanguageMenu.tsx to see how Google analytics events are added to buttons
- [ ] To ensure it is working, installing an extension like Google Analytics Debugger in Chrome is very helpful.

**Comment by SangilYun** [comment]
Hi! I'm interested in working on this issue. Would it be possible to be assigned to it?

**Comment by eleanorreem** [comment]
@SangilYun  Thank you for your interest in contributing to Chayn!
I've assigned you this issue. Please read the Contributing Guidelines and let us know if you have any questions. 🙂
