### ISSUE TITLE
Migrate all next/legacy/image imports to next/image

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#899]
### Overview
When we upgraded nextjs, we didn't migrate to the new next/image imports. This ticket is tidying up the legacy imports. 

### Action Items

- [ ] Go through the repo and replace all instances of next/legacy/image with new import of next/image.
- [ ] Check each instance and ensure it has not broken the image in UI
- [ ] Run Cypress tests 

### Resources/Instructions
See https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration section on next/image migration.

**Comment by anmol-fzr** [comment]
@eleanorreem I would like to work on this issue, please assign this to me.

**Comment by LouisVdwl** [comment]
Hey @eleanorreem, I would be happy to work on it ! Can you assign me the issue ? 😄

**Comment by kyleecodes** [comment]
Hey, thank you for your patience. @anmol-fzr I have assigned you the issue. If you would like to work on something else instead we'll assign someone else.
@LouisVdwl thank you for your interest! We have more beginner friendly issues being published soon so check back for similar issues.
