### ISSUE TITLE
Migrate the frontend to the new GET /user/me endpoint

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#906]
### Overview

We are not very compliant with REST standards. We would like to be better. This ticket focuses on the current POST /user/me endpoint. This endpoint GETs information and is not a POST request.  

### Action Items

- [ ] Look at recent [GET /user/me endpoint ](https://github.com/chaynHQ/bloom-backend/pull/419)
- [ ] Update the current implementation of the POST /user/me endpoint to a GET  request in /bloom-frontend/app/api.ts
- [ ] Ensure there are no other places where this api endpoint is used
- [ ] Run Cypress tests and post a picture of them passing. This is super important as this change will touch most functionality.

**Comment by LouisVdwl** [comment]
Hey ! I can work on it :)

**Comment by LouisVdwl** [comment]
Hey @eleanorreem ! I can work on it :)

**Comment by eleanorreem** [comment]
Hey @LouisVdwl, Thanks for your interest. Let me know if you have any questions!

**Comment by annarhughes** [comment]
This is now completed in #970
