### ISSUE TITLE
Language Menu should disappear when a user selects a language

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#910]
**Describe the bug**
The language menu does not disappear after an option has been clicked. 

**To Reproduce**

1. Go to bloom.chayn.co
2. Click on the language options
3. Select a different language
4. Note that language of page changes but the language menu dropdown does not disappear

**Expected behavior**
When I click on the language menu and select a different language, the language dropdown should disappear. 

**Screenshots**
<img width="1171" alt="Screenshot 2024-05-15 at 14 48 13" src="https://github.com/chaynHQ/bloom-frontend/assets/16049515/4eedf570-491c-4cf6-94b4-fb5c0991eb72">
<img width="980" alt="Screenshot 2024-05-15 at 14 50 47" src="https://github.com/chaynHQ/bloom-frontend/assets/16049515/db9d9e54-4dfd-47e6-aa81-86a4c1b9d746">

**Comment by anmol-fzr** [comment]
@eleanorreem  I would like to work on this issue. Please assign this issue to me

**Comment by eleanorreem** [comment]
Assigned! Let me know if you have any questions
