### ISSUE TITLE
Change colours of Breadcrumbs on session pages

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#918]
### Overview

Change colour of breadcrumbs on session pages. Previously, the breadcrumbs were changed but they weren't on the session pages.

The buttons on `Recovering from Toxic and Abuse relationships` are the wrong colour:
 
<img width="575" alt="Screenshot 2024-05-20 at 14 04 32" src="https://github.com/chaynHQ/bloom-frontend/assets/16049515/f8422636-42a3-4fd3-ad28-5976432e54d9">

They should look like:
![Screenshot 2024-05-08 at 11 18 22 (1)](https://github.com/chaynHQ/bloom-frontend/assets/16049515/b72fbd69-1516-46ef-9d74-913b5998142f)

Please note that the change was made on the course `Image-based abuse and Rebuilding ourselves`. However, this is a different template to courses like `Recovering from Toxic and Abusive` relationships.

### Action Items
- [ ] Get the UI frontend and backend up and running following readme instructions, 
- [ ] Go to /courses and go to Recovering from Toxic and Abusive relationships course. Then click on any session
- [ ] Update colour of breadcrumbs on session pages. See /bloom-frontend/pages/courses/[slug]/[sessionSlug].tsx
- [ ] Check a sample of session pages to see if they are the right colour

### Resources/Instructions
See PR #894 for previous PR which missed  out this button.

**Comment by anmol-fzr** [comment]
I would like to contribute on this issue please assign me this issue

**Comment by begench-g** [comment]
Hello. Please assign me this issue.

**Comment by begench-g** [comment]
> ### Overview
> Change colour of breadcrumbs on session pages. Previously, the breadcrumbs were changed but they weren't on the session pages.
> 
> The buttons on Recovering from Toxic and Abuse relationships are the wrong colour:
> 
> <img alt="Screenshot 2024-05-20 at 14 04 32" width="575" src="https://private-user-images.githubusercontent.com/16049515/332059438-f8422636-42a3-4fd3-ad28-5976432e54d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDk0MTgsIm5iZiI6MTcxNjM0OTExOCwicGF0aCI6Ii8xNjA0OTUxNS8zMzIwNTk0MzgtZjg0MjI2MzYtNDJhMy00ZmQzLWFkMjgtNTk3NjQzMmU1NGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDAzMzgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyOTYwZDkyNmVlOGQ5OGIzNTg1ZTQzZjIzNWRlN2UzMGJhODMxYmE4ZjE0NGRkYzA0NTA3ZWU4YmI3YzRlZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.527TUXCKbOob3fG5WcuKViqP1riUwXAOduRiiAFqQow">
> They should look like: ![Screenshot 2024-05-08 at 11 18 22 (1)](https://private-user-images.githubusercontent.com/16049515/332059484-b72fbd69-1516-46ef-9d74-913b5998142f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDk0MTgsIm5iZiI6MTcxNjM0OTExOCwicGF0aCI6Ii8xNjA0OTUxNS8zMzIwNTk0ODQtYjcyZmJkNjktMTUxNi00NmVmLTlkNzQtOTEzYjU5OTgxNDJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDAzMzgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNTUwZjM2Y2E4YzNmMjgzMzI1MTRmZThmMmQ2M2JlMTNiYzA0NTM5YmNhZWEzMGQ0MDI2Mjc4NzA3MDFhZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NoceZXCiqrqj946EBiG7a3WaO3o0EPaNNzjdua4Dz_c)
> 
> ### Action Items
> * [ ]  Get the UI frontend and backend up and running following readme instructions,
> * [ ]  Go to /courses and go to Recovering from Toxic and Abusive relationships course. Then click on any session
> * [ ]  Update colour of breadcrumbs on session pages. See /bloom-frontend/pages/courses/[slug]/[sessionSlug].tsx
> * [ ]  Check a sample of session pages to see if they are the right colour
> 
> ### Resources/Instructions
> See PR #894 for previous PR which missed out this button.

Hello. Please assign me this issue

**Comment by kyleecodes** [comment]
Hey @begench-g & @anmol-fzr! Thank you for your interest in contributing to Chayn.
Sorry this issue is reserved for Chayn's current open-source volunteer cohort.
We need to keep issues open for this program for the next month. You can check back in three weeks for more open issues!
Thanks again for your interest. See our [Getting Involved Guide](https://www.chayn.co/) for other ways to contribute to Chayn.

**Comment by ramyaparimi** [comment]
Hi! I would like to work on this issue! Please assign this to me :)

**Comment by kyleecodes** [comment]
@ramyaparimi you are assigned!

**Comment by boodland** [comment]
@kyleecodes could you assign it to me please?
