### ISSUE TITLE
Update french footer text

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#919]
### Overview

Update description of Bloom in the french site version in the footer. We store some of our translations in /messages folder. 

### Action Items
- [ ] Go to the french version of the site by navigating with the language menu at the top. Look at the footer to see the piece of text where Bloom is described. 
- [ ] Look at the /bloom-frontend/messages/shared/fr.json to find the relevant string. Update the text according to the image below:
<img width="796" alt="Screenshot 2024-05-16 at 15 50 20 - Francesca Jarvis" src="https://github.com/chaynHQ/bloom-frontend/assets/16049515/52028f23-077c-4b3f-bd5a-f8ae5a640b6a">
- [ ] Rebuild to site to ensure that it has been updated
- [ ] Run tests and linting to ensure nothing has been broken

**Comment by mayank-sahai** [comment]
Hi, I would like to help with this task.

**Comment by shashank6341** [comment]
Hi @eleanorreem I would love to work on this issue.

I have read the contributions guideline.

**Comment by kyleecodes** [comment]
@mayank-sahai, @shashank6341 we are reserving this issue for volunteers. Please check back in 3 weeks to claim this issue if it's still available. Thanks!

**Comment by robertaro90** [comment]
Hi Kylee, could I help with this task? thank you
