### ISSUE TITLE
Make course content available pre login

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#920]
### Overview

Like the bloom.chayn.co/courses page (see [PR](https://github.com/chaynHQ/bloom-frontend/pull/869)), we want make our bloom.chayn.co/courses/:slug pages available pre login so that users can understand what we offer better. 

See design below for how this would look. The only changes visually on this page would be the additional banner to sign up at the bottom. 

<img width="234" alt="Screenshot 2024-05-22 at 11 57 34" src="https://github.com/chaynHQ/bloom-frontend/assets/16049515/73837e69-7bea-49ca-a63a-9decb16ab0c9">

Please note the creating boundaries course does not exist - it was just the template for the design. 

### Action Items
- [ ] Take a look at how the courses page is implemented `bloom-frontend/pages/courses/index.ts`. You see the course list pre login. Note that currently the cards with the course names are not clickable and there is a banner below that is a CTA to sign up. 
- [ ] Ensure the course cards on the /courses are now clickable pre login and direct you to the individual course pages 
- [ ] Take a look at the individual course pages `bloom-frontend/pages/courses/[slug].tsx`
- [ ] Ensure that the/courses/:slug page is available pre login. Take a look at the authguard in _app.tsx to see how the authguard works. 
- [ ] Ensure that pre login, the cards on /courses/:slug that take you to individual sessions are not clickable. They should however remain clickable after logging in.
- [ ] At the end of the page before the footer, put a sign up CTA banner. This is the same one that is on the course page.

**Comment by GrannyYetta** [comment]
Could I get this issue assigned?

**Comment by SureshPradhana** [comment]
can I be assigned to this issue? It’s unassigned now.
