### ISSUE TITLE
Fix Typo in Contributing File

### ISSUE THREAD

**Issue by kyleecodes** [chaynHQ/bloom-frontend#936]
### Overview
For new to open-source volunteers - the word "sustainable" in the Contributing Docs[ under the Issue Limit Policies header](https://github.com/chaynHQ/bloom-frontend/blob/develop/CONTRIBUTING.md#issue-limit-policies) is misspelled and needs corrected. This issue is best for contributors new to open-source because it does not require local development. However we recommend contributors still clone the repo locally and follow all the steps in the Contributing file.

### Action Items
- [ ] Read and follow the directions in the Contributing file.
- [ ] Correct the typo: sustainble -> sustainable.
- [ ] Open a pull request.

**Comment by robertaro90** [comment]
Hi Kylee, could I work on this, please?
