### ISSUE TITLE
Open Graph Social Preview Image is not loading

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#997]
### Overview

When I share bloom.chayn.co on facebook the preview image does not load. See my example below:
<img width="250" alt="Screenshot 2024-06-26 at 10 50 11" src="https://github.com/chaynHQ/bloom-frontend/assets/16049515/e1c866ed-3c89-4b3f-bab4-df4db9f0921d">

See previous issues #916  and associated PRs where we have tried to address this. 

### Action Items
- [ ] Take a look at this [website](https://socialsharepreview.com/?url=https://bloom.chayn.co). It highlights the issues with our social share for each social media site. 
- [ ] Debug and fix social share preview
- [ ] Upload a Screen shot to show that the issue is fixed 
- [ ] Tag @kyleecodes for a review

**Comment by anmol-fzr** [comment]
Issue related to this one was assigned to me. I've fixed the issue and raised a PR
@kyleecodes Fixed the aspect-ratio issue for the og:image meta tag at PR https://github.com/chaynHQ/bloom-frontend/pull/998
